osx_image: xcode7.3

sudo: false

language: node_js

node_js:
  - "6.3.0"
  - "stable"

matrix:
  include:
    - os: osx
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang
  allow_failures:
    - node_js: "stable"

#cache:
#  directories:
#    - node_modules

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libusb-1.0-0-dev
      - icnsutils

env:
  - CXX=g++-4.8

before_install:
  - export DISPLAY=:99.0
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ( sudo Xvfb :99 -ac -screen 0 1280x1024x16; echo ok )& fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then ( /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16 )& fi
  - sleep 3

install:
  - npm install -g npm@latest
  - npm install

script:
  - npm run lint
  - npm run test
#  - npm run build
#  - npm run test-e2e
#  - npm run package
