sudo: false

language: node_js
node_js:
  - "6"
  - "stable"

before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi

script:
- npm run lint
- npm test

matrix:
  allow_failures:
    - node_js: "stable"


