sudo: false

language: node_js

node_js:
  - "6.3.0"
  - "stable"

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - git
      - gcc-4.8
      - g++-4.8
      - icnsutils
      - graphicsmagick
      - xz-utils
      - xorriso
      - g++-4.8-multilib
      - gcc-multilib
      - libgtk2.0-0
      - libxtst6
      - libnotify4
      - libgconf2-4
      - libgtk2.0-0:i386
      - libxtst6:i386
      - libnotify4:i386
      - libgconf2-4:i386
      - libnss3:i386
      - libasound2:i386
      - libxss1:i386
      - socat
      - libusb-1.0-0:i386
      - libusb-1.0-0-dev
      - libudev-dev

env:
  - CXX=g++-4.8

before_install:
  - export DISPLAY=:99.0
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - sleep 3

install:
  - npm install -g npm@latest
  - npm install

script:
  - npm run lint
  - npm run test
  - npm run build
  - npm run test-e2e
  - npm run package

matrix:
  allow_failures:
    - node_js: "stable"
