image: Visual Studio 2017

environment:
  APPVEYOR_CACHE_ENTRY_ZIP_ARGS: -t7z
  matrix:
    - nodejs_version: 7.4.0

cache:
  - node_modules -> package.json
  - app/node_modules -> app/package.json
#  - "%LOCALAPPDATA%\\Yarn"

platform:
  - x64

matrix:
  fast_finish: true

build: off

version: '{build}'

shallow_clone: true

clone_depth: 1

install:
  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
  - ps: Update-AppveyorBuild -Version "$env:package_version-$env:APPVEYOR_BUILD_NUMBER"
  - ps: Install-Product node $env:nodejs_version $env:platform
  - set CI=true
  - node ./yarn-1.0.2.js --frozen-lockfile --offline

test_script:
  - node --version
  - node ./yarn-1.0.2.js lint
  - node ./yarn-1.0.2.js test
#  - yarn test-e2e
#  - node ./yarn-1.0.2.js package-dev
#  - 7z a development.zip release
#  - rmdir /S /Q release
  - node ./yarn-1.0.2.js package
#  - 7z a production.zip release

notifications:
  - provider: Slack
    incoming_webhook:
      # webhook URL is encrypted so can be stored in public repo
      secure: PkO2WgPHg816yzPsyT47fxuBlM5bGhsNUn+VaNmLU6zCC31xwttRteKybldC6Jp1kdlWALyRdxt7WYsWDrkrAG3tHYSHSo7RDhea4qLuwjA=
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: false

#artifacts:
#  - path: development.zip
#    name: Development build
#  - path: production.zip
#    name: Production Build
