os: unstable

environment:
  matrix:
    - nodejs_version: 6.3.0
    - nodejs_version: 7

cache:
  - node_modules -> package.json
  - app/node_modules -> app/package.json

# Enable when https://github.com/yarnpkg/yarn/issues/1233 and
# https://github.com/yarnpkg/yarn/issues/1059 are resolved and disable npm cache
#
# cache:
#   - "%LOCALAPPDATA%/Yarn"

platform:
  - x64

matrix:
  fast_finish: true
  allow_failures:
    - nodejs_version: 7

build: off

version: '{build}'

shallow_clone: true

clone_depth: 1

install:
  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
  - ps: Update-AppveyorBuild -Version "$env:package_version-$env:APPVEYOR_BUILD_NUMBER"
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - npm install -g npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install

# Enable when https://github.com/yarnpkg/yarn/issues/1233 and
# https://github.com/yarnpkg/yarn/issues/1059 are resolved and disable npm cache
#
# install:
#   - ps: Install-Product node $env:nodejs_version
#   - set CI=true
#   - choco install yarn
#   - refreshenv
#   - yarn

test_script:
  - node --version
  - npm run lint
  - npm run test
#  - npm run build
#  - npm run test-e2e
  - npm run package-dev -- --ia32 --x64
  - 7z a development.zip release
  - npm run package -- --ia32 --x64
  - 7z a production.zip release


artifacts:
  - path: development.zip
    name: Development build
  - path: production.zip
    name: Production Build
